name: 💡 Event Proposal
description: Propose a new event (workshop, talk, hackathon, etc.) for the HiredX Full-stack Club.
title: "[EVENT PROPOSAL] - "
labels: ["event-proposal", "new-event"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 💡 Event Proposal: [Your Proposed Event Title Here]

        Thank you for proposing an event for the HiredX Full-stack Club! Please fill out the details below as thoroughly as possible. This will help us evaluate, plan, and organize your event effectively.

  - type: input
    id: event-title
    attributes:
      label: Proposed Event Title
      description: E.g., "Advanced React Hooks Workshop", "Backend API Design with Rust", "Full-stack Project Brainstorm Session"
      placeholder: Enter your event title
    validations:
      required: true

  - type: input
    id: date-time
    attributes:
      label: Proposed Date(s) & Time(s) (with Timezone)
      description: E.g., "Saturday, July 20, 2025, 10:00 AM - 1:00 PM PST". Consider our common locations/platforms and their availability.
      placeholder: Enter date(s) and time(s)
    validations:
      required: true

  - type: dropdown
    id: platform-location
    attributes:
      label: Preferred Platform/Location
      description: Refer to our common locations/platforms for options.
      options:
        - MS Teams (Primary Virtual)
        - Vancouver Public Library - Central Branch (Preferred Weekend In-person)
        - UBC Biomedical Branch Library (Mon-Fri 11 AM-4 PM In-person)
        - Zoom (Backup Virtual)
        - Google Meet (Backup Virtual)
        - Other (please specify in description)
    validations:
      required: true

  - type: dropdown
    id: event-type
    attributes:
      label: Event Type
      options:
        - Workshop
        - Technical Talk
        - Q&A Session
        - Coding Challenge
        - Panel Discussion
        - Networking Event
        - Project Brainstorm
        - Other (please specify in description)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Brief Description
      description: A concise summary of what the event is about and its main goal for attendees.
      placeholder: Describe your event here...
    validations:
      required: true

  - type: textarea
    id: agenda
    attributes:
      label: Detailed Agenda / Topics to Cover
      description: Outline the main topics, activities, or flow of the event. Be as specific as possible.
      placeholder: |
        - Topic 1: ...
        - Topic 2: ...
        - Activity: ...
        - Q&A
    validations:
      required: true

  - type: textarea
    id: target-audience
    attributes:
      label: Target Audience & Prerequisites
      description: |
        - Who is this event for? (e.g., "Beginner React developers", "Developers interested in backend performance", "All full-stack members")
        - What should attendees know/have beforehand? (e.g., "Basic JavaScript knowledge", "Laptop with Node.js installed", "Familiarity with Git")
      placeholder: Who is this for and what do they need?
    validations:
      required: true

  - type: textarea
    id: speaker-details
    attributes:
      label: Speaker / Presenter Details
      description: |
        - Your Name / Speaker's Name:
        - Brief Bio (1-2 sentences): (e.g., "Experienced full-stack developer specializing in [X] and [Y].")
        - Relevant Experience/Expertise: (Why are you/they a good fit to lead this event?)
      placeholder: Provide speaker info here...
    validations:
      required: true

  - type: textarea
    id: resources-needed
    attributes:
      label: Resources Needed / Support Required
      description: |
        - Technical Setup: (e.g., "Projector", "Whiteboard", "Stable internet", "Specific software licenses")
        - Promotional Support: (e.g., "Need help creating graphics", "Announcement in WhatsApp")
        - Mentors/Helpers: (Do you need other members to assist during the event?)
        - Any other specific requests?
      placeholder: What resources do you need from the club?
    validations:
      required: false

  - type: checkboxes
    id: proposer-checklist
    attributes:
      label: Proposer Checklist
      options:
        - label: I have read and understand the [HiredX Full-stack Club Code of Conduct](https://github.com/HiredX-Fullstack-Club/.github/blob/main/CODE_OF_CONDUCT.md).
          required: true
        - label: I have checked the [common event locations and platforms](https://github.com/HiredX-Fullstack-Club/events/blob/main/locations.md) for suitability.
          required: true
        - label: I am available to discuss this proposal further.
          required: true

  - type: markdown
    attributes:
      value: |
        ---
        **Thank you for helping us grow the HiredX Full-stack Club!**